# Generated by Django 3.0.9 on 2020-08-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200819_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='division',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='region',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
