# Generated by Django 3.0.9 on 2020-08-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200819_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
