# Generated by Django 3.0.9 on 2020-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_myuser_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='should_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
