# Generated by Django 3.0.9 on 2020-08-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200820_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
