# Generated by Django 3.0.9 on 2020-08-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200820_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='region',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Division'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Position'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Unit'),
            preserve_default=False,
        ),
    ]
