# Generated by Django 3.0.9 on 2020-08-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0005_auto_20200820_0719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
