# Generated by Django 3.0.9 on 2020-08-22 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0008_auto_20200820_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentedInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2020)),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='file_manager.DocumentType')),
                ('secretariat_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='file_manager.SecratariatLevel')),
            ],
        ),
    ]
