# Generated by Django 3.0.9 on 2020-08-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0010_auto_20200822_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentedinformation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
