# Generated by Django 3.0.9 on 2020-08-24 00:04

from django.db import migrations, models
import file_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0011_documentedinformation_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentedinformation',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RemoveField(
            model_name='documentedinformation',
            name='description',
        ),
        migrations.AlterField(
            model_name='documentedinformation',
            name='file',
            field=models.FileField(upload_to=file_manager.models.DocumentedInformation.upload_folder),
        ),
    ]
