# Generated by Django 3.0.9 on 2020-08-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0014_auto_20200824_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsForApproval',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('file_manager.documentedinformation',),
        ),
    ]
