# Generated by Django 3.0.9 on 2020-08-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
    ]
