# Generated by Django 3.0.9 on 2020-09-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0002_remove_event_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='all_day',
            new_name='allDay',
        ),
    ]
