from account.models import Division, Position, Unit
from file_manager.models import DocumentType, SecratariatLevel

Division.objects.create(name="Office of the Executive Director")
Division.objects.create(name="Advocacy and Communication Division")
Division.objects.create(name="National Coordination Monitoring and Inofrmation Mangament Division")
Division.objects.create(name="Policy and Research Division")
Division.objects.create(name="Finance and Administrative Division")
Division.objects.create(name="RJJWC CAR")
Division.objects.create(name="RJJWC NCR")
Division.objects.create(name="RJJWC I")
Division.objects.create(name="RJJWC II")
Division.objects.create(name="RJJWC III")
Division.objects.create(name="RJJWC IV-A")
Division.objects.create(name="RJJWC IV-B")
Division.objects.create(name="RJJWC V")
Division.objects.create(name="RJJWC VI")
Division.objects.create(name="RJJWC VII")
Division.objects.create(name="RJJWC VIII")
Division.objects.create(name="RJJWC IX")
Division.objects.create(name="RJJWC X")
Division.objects.create(name="RJJWC XI")
Division.objects.create(name="RJJWC XII")
Division.objects.create(name="RJJWC CARAGA")
Division.objects.create(name="RJJWC BARMM")

Position.objects.create(name="Executive Director")
Position.objects.create(name="Deputy Executive Director")
Position.objects.create(name="Project Development Officer IV")
Position.objects.create(name="Executive Assistant II")
Position.objects.create(name="UNICEF Coordinator")
Position.objects.create(name="Administrative Assistant III")
Position.objects.create(name="Administrative Assistant II")
Position.objects.create(name="Administrative Aide IV")
Position.objects.create(name="Social Welfare Officer V")
Position.objects.create(name="Project Development Officer III")
Position.objects.create(name="Social Welfare Officer III")
Position.objects.create(name="Project Development Officer II")
Position.objects.create(name="Social Welfare Officer IV")
Position.objects.create(name="Information Technology Officer II")
Position.objects.create(name="Information Technology Officer I")
Position.objects.create(name="Statistician III")
Position.objects.create(name="Chief Administrative Officer ")
Position.objects.create(name="Accountant III")
Position.objects.create(name="Administrative Officer II")
Position.objects.create(name="Administrative Officer V")
Position.objects.create(name="Administrative Officer IV")
Position.objects.create(name="Administrative Assistant")

Unit.objects.create(name="Accounting Unit")
Unit.objects.create(name="Budget and Cash Unit")
Unit.objects.create(name="General Services Unit / Property and Supply Unit")
Unit.objects.create(name="HR / Personnel Unit")
Unit.objects.create(name="Procurement Unit")
Unit.objects.create(name="Records Unit")
Unit.objects.create(name="Other")

DocumentType.objects.create(type='JJWC WFP', description='JJWC WFP')
DocumentType.objects.create(type='RJJWC WFP', description='RJJWC WFP')
DocumentType.objects.create(type='Division WFP', description='Division WFP')
DocumentType.objects.create(type='Internal Issuances', description='Internal Issuances')
DocumentType.objects.create(type='CNJIP', description='CNJIP')
DocumentType.objects.create(type='CRJIP', description='CRJIP')
DocumentType.objects.create(type='National Situational Analysis Report on CICL and CAR ', description='National Situational Analysis Report on CICL and CAR ')
DocumentType.objects.create(type='Regional Situational Analysis Report on CICL and CAR', description='Regional Situational Analysis Report on CICL and CAR')
DocumentType.objects.create(type='Position Papers', description='Position Papers')
DocumentType.objects.create(type='Downloadable forms', description='Downloadable forms')
DocumentType.objects.create(type='Division Accomplishment Reports', description='Division Accomplishment Reports')
DocumentType.objects.create(type='RJJWC Accomplishment Reports ', description='RJJWC Accomplishment Reports ')
DocumentType.objects.create(type='Status of JJWA Implementation Report', description='Status of JJWA Implementation Report')
DocumentType.objects.create(type='Statistics', description='Statistics')
DocumentType.objects.create(type='List of LGUs with CLJIP', description='List of LGUs with CLJIP')


SecratariatLevel.objects.create(level='National')
SecratariatLevel.objects.create(level='Regional')

